### ISSUE TITLE
Making the project more integrated with web development practices (adding npm, webpack support)

### ISSUE THREAD

**Issue by crisbal** [lays147/PWAPlanet#3]
Hey Lays, nice project!

I am a fellow KDE developer (I am a Web Developer for WikiToLearn), and found out about your project on KDE Planet. It looks good so far but I think it could really use a better integration with the Javascript world. 

I think it could be beneficial to the code if we would manage dependencies with npm (so we can keep them up-to-date with ease and we can keep the external files out of the repo) and also introduce a build script with [Webpack](https://webpack.js.org/), this will mostly take care of minification for both the Javascript and the CSS, resulting in a smaller code size for the final user.

As a downside of using Webpack it will require an additional step before deployment to your server (you would have to run a command to "build" the website) but at the same time we would speed up development (Webpack allows for live reloading changes during development).

Let me know what you think, if they seems ok with you I will implement these. These changes are not necessary right now but nowadays are seen as good practices for web apps.

**Comment by lays147** [comment]
Hey, thanks for this feedback!
When I made this app, it was just for the fun to learn new stuff. I don't have JS expertise so I don't know what can improve and what can't improve my app.
You can go ahead and work into it. We can use travis to build the app inside github and deploy on the gh pages.

**Comment by crisbal** [comment]
Hey, I started to work on this. You can find the repo here: https://github.com/crisbal/PWAPlanet

As of right now everything seems to work the same way it does on the main website (except for the colors of the theme which I have yet to fix)

I included some instructions in the README on how to build/test the project using the new build process, don't be scared if you see that the structure has changed a lot. 
The code was split between the `src/` folder (for the main script) and the `static/` folder (for all the files that needs to be served without any pre-processing).
I included some comments in the `webpack.config.js` file so you can get an idea on how the build script works.
All the external dependencies (materializelite and materialicons) are now managed by the npm package manager, that's why their files are no more in the repo.

I will propose a PR later on, in the meanwhile let me know if you have any issue with the changes.

EDIT: I also fixed the color now!

**Comment by lays147** [comment]
Hey @crisbal any updates on your work?

**Comment by crisbal** [comment]
Hey, thanks for reminding me. Most of the work is complete. Right now the only thing missing is a deployment script for Travis CI that will automatically deploy on the `gh-pages` branch. I will work on this now.

**Comment by lays147** [comment]
awesome! =D

**Comment by lays147** [comment]
@crisbal You forgot to update the version of the index.html file. 
Also, the icons aren't being loaded, at least the ones on the main page(reload and hamburger buttons)

**Comment by crisbal** [comment]
Hey Lays, I was AFK because of New Years celebrations. I will take a look at this in the next days. We should open new issues for the two bugs you found. On my machine I am sure it was working.

**Comment by crisbal** [comment]
Ok it was working because I had the fonts installed on my pc  -.-. 

The problem with the hamburger menu is that it requires the official material icons font (the one served from google fonts) since it is dynamically added. 

We should include ```<link href="https://fonts.googleapis.com/icon?family=Material+Icons"
      rel="stylesheet">``` so it will render correctly. This is not optimal (since two icon fonts are loaded) but I think it is what was done before. 

The best way would be to use either the `mdi` (which has support for social icons) or `Material Icons by Google` which is the one needed by `material-design-lite`.

**Comment by lays147** [comment]
The problem with that include would be that the burger icon won't show if the app is offline. However, the person will be only able to read the posts if it's online. So apparently we won't have much problem... (Also, who gets offline these days?)
